'''
line types in hy3 files
'''


# class HY3Line(type): ...

# # file info
# class A1(metaclass = HY3Line): ...

# # meet info
# class B1(metaclass = HY3Line):...
# class B2(metaclass = HY3Line): ...

# # team info
# class C1(metaclass = HY3Line): ...
# class C2(metaclass = HY3Line): ...
# class C3(metaclass = HY3Line): ...

# # swimmer info
# class D1(metaclass = HY3Line): ...

# # individual event info
# class E1(metaclass = HY3Line): ...
# class E2(metaclass = HY3Line): ...

# # relay event info
# class F1(metaclass = HY3Line): ...
# class F2(metaclass = HY3Line): ...
# class F3(metaclass = HY3Line): ...

# # split info
# class G1(metaclass = HY3Line): ...

# # DQ info
# class H1(metaclass = HY3Line): ...




if __name__ == '__main__':

    ...